@startuml

class Cabinet {
nom : NomGenerique 
adresse : Adresse 
infirmiers : List<Infirmiers>
patients : List<Patient>
}

/' les classes conteneurs de patien et infirmier'/
class Patients{
patient : List<Patient>
}

class Infirmiers{
Infirmier : List<Infirmier>
}


class Patient{
nom : Nomgenerique
prenom : NomGenerique
sexe : Sexe 
dateNaissance : date
numero : numSecu
adresse : Adresse
visite : List<Visite>
}

class Infirmier{
id : Identifiant 
nom : NomGenerique
prénom : NomGenerique
photo : Photo
}

class Visite{
date : Date
intervenant : Identifiant /' id de l'infirmier intervenu'/
acte : List<Acte>
}

class Acte{
id : Identifiant 
intitule: String
lettreCle: LettreCle
coefficient: double

}


class Adresse{
etage: NombreEntier "optionnel"
numero: NombreEntier
rue: Rue 
codePostal: NumbreEntier
ville: NomGenerique
}

class Rue{
nom: NomGenerique
typeVoie: TypeVoie
}

/' NomGenerique: passer en classe : nom, prenom, ville '/
class NomGenerique {
} 


/' Identifiant: 3 chiffres, ex: 001-999 '/
class Identifiant{
}

/' NombreEntier: entier >=0 '/
class NombreEntier{
}

/' Sexe: M ou F '/
class Sexe{
}

/'numSecu: composé de 13 chiffres, suivi d’une clé de contrôle
 de 2 chiffres  comprise entre 01 et 97 '/
class numSecu{
}

/'extension .jpg | .png '/
class Photo{
}

/'TypeVoie: enumération '/
class TypeVoie{
}




/'les relations '/

/'la Composition (*--): La "partie" ne peut pas exister sans le "tout"
exemple: Cabinet -> la "Tout" , Infirmiers -> la "Partie"
si le cabinet ferme, plus la classe Infirmiers(plus de raison d'etre)
'/

/'L'Agrégation (o--): La "partie" peut exister indépendamment du "tout"
'/

/' A --> B : A -> (A l'element simple , B -> l'element qui utilise A) lien logique simple qui peut signifier "est affecteé à"
 '/


Cabinet *-- Infirmiers
Cabinet *-- Patients
Cabinet *-- "1" Adresse 

Infirmiers *-- "1..*" Infirmier

Patients *-- "1..*" Patient
Patient *-- "0..*" Visite /'une visite ne peut pas exister sans patient '/
Patient "0..*" --> "1" Infirmier /' 1 Infirmier a 0 ou +sieur Patient '/

Visite *-- "1..*"  Acte 

NomGenerique --> Cabinet 
NomGenerique --> Infirmier
NomGenerique --> Patient /'nom + Prénom'/
NomGenerique --> Adresse  /'Ville'/
NombreEntier --> Adresse  /'CodePostal'/
numSecu --> Patient 

Sexe--> Patient
Adresse "1" --> Patient
Identifiant --> Infirmier
Photo --> Infirmier
Rue --> Adresse






@enduml
